M48
; DRILL file {KiCad 7.0.6} date Sun Aug 13 13:31:49 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-13T13:31:49-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.502Y-2.9307
T2
X4.88Y-2.67
X4.88Y-4.78
X8.125Y-2.67
X8.125Y-4.78
T0
M30
